apiVersion: apps/v1
kind: Deployment
metadata:
  name: risk-scoring-engine
spec:
  replicas: 1
  selector:
    matchLabels:
      app: risk-scoring-engine
  template:
    metadata:
      labels:
        app: risk-scoring-engine
    spec:
      containers:
      - name: risk-scoring-engine
        image: risk-scoring-engine:latest
        ports:
        - containerPort: 5003
        env:
        - name: MONGO_URI
          value: mongodb://mongo:27017/
---
apiVersion: v1
kind: Service
metadata:
  name: risk-scoring-engine
spec:
  selector:
    app: risk-scoring-engine
  ports:
    - protocol: TCP
      port: 5003
      targetPort: 5003